// PollyController — data only. UI is rendered by PollyCard inside MaskBoard.

export const BUDGET: Record<string, number> = {
  intro:        1.5,
  perfect:      0.8,
  nearMiss:     1.0,
  bossEntry:    0.5,
  bossWord:     1.5,
  streak5:      0.3,
  locked:       1.0,
  cleanSplit:   1.2,
  hiddenReveal: 2.0,
  slangDrop:         1.2,
  slangCorrect:      1.0,
  slangMiss:         1.0,
  switchback:        1.5,
  switchbackFirst:   0.8,
  switchbackSecond:  0.8,
  switchbackFail:    2.0,
  ghostIntro:        1.8,
  ghostCorrect:      1.0,
  ghostWrong:        1.0,
};

export const POLLY_LINES: Record<string, string> = {
  // intro is computed dynamically per-word in PollyCard
  perfect:      "Something's hiding in this one.",
  nearMiss:     'Close, but no cigar.',
  bossEntry:    'This one bites back.',
  bossWord:     'This one bites back.',
  streak5:      "You're on fire.",
  locked:       'Locked.',
  cleanSplit:   'Two real, two fakes.',
  hiddenReveal: 'Hidden. Worth it.',
  slangDrop:        'Slang check.',
  slangCorrect:     'Language moves.',
  slangMiss:        'Not quite street.',
  switchback:       'One word. Two lives.',
  switchbackFirst:  'Sharp.',
  switchbackSecond: 'Got there.',
  switchbackFail:   '',
  ghostIntro:       'This one followed you.',
  ghostCorrect:     'Redeemed.',
  ghostWrong:       'Still haunting you.',
};
