import { DailyWord } from './types';

export const DAILY_POOL: DailyWord[] = [
  {
    word: "BARK",
    meanings: [
      "THREE-MASTED SAILING SHIP",
      "A TREE’S OUTER COVERING",
      "A DOG’S SHARP WARNING",
    ],
    candidates: [
      "HULL",
      "HOWL",
      "TRUNK",
      "RIND",
      "BARK",
      "BARGE",
      "WOOD",
      "GROWL",
      "YELP",
    ],
    tier: 1,
  },
  {
    word: "RING",
    meanings: [
      "WHERE BOXERS TRADE PUNCHES",
      "WORN ON THE FOURTH FINGER",
      "WHAT A DOORBELL DOES",
    ],
    candidates: [
      "ARENA",
      "BAND",
      "CHIME",
      "ROUND",
      "RING",
      "BRACELET",
      "BUZZ",
      "LOOP",
      "GONG",
    ],
    tier: 1,
  },
  {
    word: "MATCH",
    meanings: [
      "STRUCK TO START A FLAME",
      "AN EQUAL OPPONENT",
      "A CONTEST BETWEEN TWO SIDES",
    ],
    candidates: [
      "SPARK",
      "RIVAL",
      "GAME",
      "LIGHTER",
      "MATCH",
      "PAIR",
      "TIE",
      "FIGHT",
      "TWIN",
    ],
    tier: 1,
  },
  {
    word: "SPRING",
    meanings: [
      "WATER FLOWING FROM THE GROUND",
      "METAL COIL THAT BOUNCES BACK",
      "THE SEASON AFTER WINTER",
    ],
    candidates: [
      "WELL",
      "SHOCK",
      "SUMMER",
      "CREEK",
      "SPRING",
      "WIRE",
      "FOUNTAIN",
      "PISTON",
      "FALL",
    ],
    tier: 1,
  },
  {
    word: "PITCH",
    meanings: [
      "A SALESMAN’S QUICK PERSUASION",
      "HOW HIGH OR LOW A SOUND IS",
      "SENT FROM THE MOUND TO HOME",
    ],
    candidates: [
      "TONE",
      "SPIEL",
      "FASTBALL",
      "KEY",
      "PITCH",
      "OFFER",
      "NOTE",
      "THROW",
      "AD",
    ],
    tier: 1,
  },
  {
    word: "PLANT",
    meanings: [
      "SECRETLY PUT THERE TO FOOL YOU",
      "AN INDUSTRIAL FACILITY",
      "NEEDS WATER AND SUNLIGHT",
    ],
    candidates: [
      "SPY",
      "FACTORY",
      "FLOWER",
      "MOLE",
      "PLANT",
      "TREE",
      "DECOY",
      "MILL",
      "SHRUB",
    ],
    tier: 1,
  },
  {
    word: "FINE",
    meanings: [
      "MONEY OWED AS A PENALTY",
      "VERY THIN OR DELICATE",
      "CLEAR WEATHER WITH NO RAIN",
    ],
    candidates: [
      "FEE",
      "SLENDER",
      "SUNNY",
      "TICKET",
      "FINE",
      "SHEER",
      "CHARGE",
      "FRAGILE",
      "DRY",
    ],
    tier: 1,
  },
  {
    word: "WAKE",
    meanings: [
      "A GATHERING BEFORE THE BURIAL",
      "TRAIL OF WATER LEFT BEHIND A SHIP",
      "OPEN YOUR EYES AFTER SLEEP",
    ],
    candidates: [
      "VIGIL",
      "RIPPLE",
      "ALARM",
      "SERVICE",
      "WAKE",
      "SWELL",
      "CURRENT",
      "DAWN",
      "RISE",
    ],
    tier: 1,
  },
  {
    word: "WAVE",
    meanings: [
      "A CURL IN YOUR HAIR",
      "A HAND MOTION FOR HELLO",
      "WHAT SURFERS RIDE",
    ],
    candidates: [
      "PERM",
      "BRAID",
      "SALUTE",
      "NOD",
      "WAVE",
      "TIDE",
      "SWELL",
      "BREAKER",
      "GESTURE",
    ],
    tier: 1,
  },
  {
    word: "SPELL",
    meanings: [
      "A BRIEF STRETCH OF COLD WEATHER",
      "A WITCH’S MAGIC INCANTATION",
      "PUT LETTERS IN THE RIGHT ORDER",
    ],
    candidates: [
      "SNAP",
      "HEX",
      "WRITE",
      "STINT",
      "SPELL",
      "CURSE",
      "CHARM",
      "ALPHABET",
      "TYPE",
    ],
    tier: 1,
  },
  {
    word: "CHARGE",
    meanings: [
      "A FORMAL ACCUSATION OF A CRIME",
      "WHAT A BULL DOES HEAD-FIRST",
      "PUT ENERGY BACK INTO YOUR PHONE",
    ],
    candidates: [
      "INDICTMENT",
      "STAMPEDE",
      "PLUG",
      "ALLEGATION",
      "CHARGE",
      "VOLTAGE",
      "RUSH",
      "BOOST",
      "CURRENT",
    ],
    tier: 2,
  },
  {
    word: "BEAR",
    meanings: [
      "A TRADER BETTING PRICES WILL FALL",
      "TO PUT UP WITH SOMETHING AWFUL",
      "HIBERNATES THROUGH THE WINTER",
    ],
    candidates: [
      "BULL",
      "SHORT",
      "WOLF",
      "COPE",
      "BEAR",
      "STOCK",
      "MOOSE",
      "SUFFER",
      "SELL",
    ],
    tier: 2,
  },
  {
    word: "PRESS",
    meanings: [
      "THE MACHINE THAT REVOLUTIONIZED PRINTING",
      "PEOPLE WRITING THE HEADLINES",
      "HOW YOU MAKE A BUTTON WORK",
    ],
    candidates: [
      "COPIER",
      "MEDIA",
      "PUSH",
      "TYPESETTER",
      "PRESS",
      "NEWS",
      "REPORTER",
      "TAP",
      "CLICK",
    ],
    tier: 2,
  },
  {
    word: "BANK",
    meanings: [
      "HOW A PLANE LEANS THROUGH A TURN",
      "LAND BESIDE A RIVER",
      "WHERE PAYCHECKS GET DEPOSITED",
    ],
    candidates: [
      "TILT",
      "SHORE",
      "VAULT",
      "ROLL",
      "BANK",
      "ATM",
      "SLOPE",
      "LEVEE",
      "CREDIT",
    ],
    tier: 2,
  },
  {
    word: "TABLE",
    meanings: [
      "PUT A PROPOSAL ASIDE UNTIL LATER",
      "DATA ARRANGED IN ROWS AND COLUMNS",
      "WHERE YOU SIT DOWN TO EAT",
    ],
    candidates: [
      "DEFER",
      "CHART",
      "DESK",
      "POSTPONE",
      "TABLE",
      "GRID",
      "LIST",
      "COUNTER",
      "BENCH",
    ],
    tier: 2,
  },
  {
    word: "DRAFT",
    meanings: [
      "AN EARLY COPY BEFORE THE FINAL ONE",
      "COLD AIR SNEAKING UNDER A DOOR",
      "BEER SERVED STRAIGHT FROM THE TAP",
    ],
    candidates: [
      "OUTLINE",
      "BREEZE",
      "LAGER",
      "SKETCH",
      "DRAFT",
      "PINT",
      "PROOF",
      "GUST",
      "ALE",
    ],
    tier: 2,
  },
  {
    word: "RANK",
    meanings: [
      "SMELLING FOUL ENOUGH TO NOTICE",
      "YOUR PLACE IN THE CHAIN OF COMMAND",
      "SOLDIERS STANDING SIDE BY SIDE",
    ],
    candidates: [
      "REEK",
      "STATUS",
      "LINE",
      "ROTTEN",
      "RANK",
      "GRADE",
      "FORMATION",
      "LEVEL",
      "FILE",
    ],
    tier: 2,
  },
  {
    word: "SEAL",
    meanings: [
      "OFFICIAL MARK THAT PROVES AUTHENTICITY",
      "KEEPS A CONTAINER TIGHTLY CLOSED",
      "MARINE MAMMAL WITH FLIPPERS",
    ],
    candidates: [
      "EMBLEM",
      "LID",
      "OTTER",
      "CREST",
      "SEAL",
      "GASKET",
      "SIGNATURE",
      "CAP",
      "WALRUS",
    ],
    tier: 2,
  },
  {
    word: "CAPITAL",
    meanings: [
      "MONEY USED TO FUND A BUSINESS",
      "A CITY WHERE GOVERNMENT IS BASED",
      "AN UPPERCASE LETTER",
    ],
    candidates: [
      "CASH",
      "METROPOLIS",
      "INITIAL",
      "ASSET",
      "CAPITAL",
      "SYMBOL",
      "FUNDS",
      "STATE",
      "TITLE",
    ],
    tier: 2,
  },
  {
    word: "CAST",
    meanings: [
      "THE ACTORS IN A MOVIE",
      "WHAT HOLDS A BROKEN ARM STILL",
      "THROW A FISHING LINE INTO THE WATER",
    ],
    candidates: [
      "CREW",
      "SPLINT",
      "REEL",
      "STAR",
      "CAST",
      "ROD",
      "ENSEMBLE",
      "BRACE",
      "TOSS",
    ],
    tier: 3,
  },
  {
    word: "SOUND",
    meanings: [
      "A BODY OF WATER BETWEEN LAND MASSES",
      "SOLID AND IN GOOD CONDITION",
      "WHAT YOUR EARS PICK UP",
    ],
    candidates: [
      "CHANNEL",
      "STURDY",
      "NOISE",
      "STRAIT",
      "SOUND",
      "HEALTHY",
      "BAY",
      "ROBUST",
      "ECHO",
    ],
    tier: 3,
  },
  {
    word: "STRIKE",
    meanings: [
      "WHEN EMPLOYEES REFUSE TO WORK",
      "ALL TEN PINS WITH THE FIRST BALL",
      "WHEN AN ANSWER SUDDENLY COMES TO YOU",
    ],
    candidates: [
      "UNION",
      "SPARE",
      "FLASH",
      "WALKOUT",
      "STRIKE",
      "HUNCH",
      "PROTEST",
      "GUTTER",
      "INSPIRATION",
    ],
    tier: 3,
  },
  {
    word: "DRAW",
    meanings: [
      "TAKE A WEAPON FROM ITS HOLSTER",
      "CREATE AN IMAGE WITH A PENCIL",
      "A CONTEST WITH NO WINNER",
    ],
    candidates: [
      "REACH",
      "SKETCH",
      "TIE",
      "FIRE",
      "DRAW",
      "DOODLE",
      "AIM",
      "ART",
      "STALEMATE",
    ],
    tier: 3,
  },
  {
    word: "GROUND",
    meanings: [
      "A REASON USED TO SUPPORT A CLAIM",
      "COFFEE AFTER THE BEANS ARE CRUSHED",
      "THE SURFACE UNDER YOUR FEET",
    ],
    candidates: [
      "EVIDENCE",
      "POWDER",
      "FLOOR",
      "BASIS",
      "GROUND",
      "EARTH",
      "PROOF",
      "ROAST",
      "SOIL",
    ],
    tier: 3,
  },
  {
    word: "MEAN",
    meanings: [
      "THE AVERAGE OF A SET OF NUMBERS",
      "WHAT YOU PLAN TO DO",
      "NOT VERY NICE TO SOMEONE",
    ],
    candidates: [
      "MEDIAN",
      "AIM",
      "NASTY",
      "MODE",
      "MEAN",
      "INTEND",
      "TOTAL",
      "EXPECT",
      "RUDE",
    ],
    tier: 3,
  },
  {
    word: "CURRENT",
    meanings: [
      "HAPPENING OR TRUE RIGHT NOW",
      "WATER PULLING YOU DOWNSTREAM",
      "ELECTRICITY MOVING THROUGH A WIRE",
    ],
    candidates: [
      "LATEST",
      "TIDE",
      "VOLTAGE",
      "MODERN",
      "CURRENT",
      "POWER",
      "PRESENT",
      "RIVER",
      "CHARGE",
    ],
    tier: 3,
  },
  {
    word: "FIELD",
    meanings: [
      "TAKE QUESTIONS FROM REPORTERS",
      "A SUBJECT YOU SPECIALIZE IN",
      "OPEN LAND USED FOR CROPS",
    ],
    candidates: [
      "ANSWER",
      "DOMAIN",
      "FARM",
      "RESPOND",
      "FIELD",
      "MAJOR",
      "HANDLE",
      "MEADOW",
      "PASTURE",
    ],
    tier: 3,
  },
  {
    word: "SET",
    meanings: [
      "WHAT CONCRETE DOES AS IT HARDENS",
      "ONE PART OF A TENNIS MATCH",
      "WHEN THE SUN DROPS BELOW THE HORIZON",
    ],
    candidates: [
      "CURE",
      "ROUND",
      "DUSK",
      "DRY",
      "SET",
      "GAME",
      "READY",
      "GROUP",
      "DESCEND",
    ],
    tier: 3,
  },
  {
    word: "RUN",
    meanings: [
      "BE IN CHARGE OF A BUSINESS",
      "WHEN COLORS BLEED IN THE WASH",
      "A RIP IN A STOCKING",
    ],
    candidates: [
      "MANAGE",
      "FADE",
      "LADDER",
      "OPERATE",
      "RUN",
      "STAIN",
      "SNAG",
      "HOLE",
      "DYE",
    ],
    tier: 3,
  },
  {
    word: "STAGE",
    meanings: [
      "PUT ON A PROTEST",
      "ONE PHASE OF A PROCESS",
      "WHERE PERFORMERS TAKE THEIR BOWS",
    ],
    candidates: [
      "PLATFORM",
      "ROUND",
      "SHOW",
      "PERIOD",
      "STAGE",
      "RALLY",
      "SCENE",
      "LEVEL",
      "STEP",
    ],
    tier: 2,
  },
  {
    word: "BLAZE",
    meanings: [
      "MARK A TRAIL THROUGH THE WOODS",
      "A BRILLIANT BURST OF COLOR",
      "A LARGE RAGING FIRE",
    ],
    candidates: [
      "PATH",
      "NOTCH",
      "FLASH",
      "ROUTE",
      "BLAZE",
      "SPECTRUM",
      "INFERNO",
      "GLOW",
      "BONFIRE",
    ],
    tier: 2,
  },
  {
    word: "BLIND",
    meanings: [
      "A HUNTER'S HIDDEN SHELTER",
      "COVERING YOU LOWER OVER A WINDOW",
      "UNABLE TO SEE",
    ],
    candidates: [
      "CURTAIN",
      "BUNKER",
      "SHADE",
      "SCREEN",
      "BLIND",
      "CAMOUFLAGE",
      "SHUTTER",
      "DARKNESS",
      "DEAF",
    ],
    tier: 2,
  },
  {
    word: "BOND",
    meanings: [
      "MONEY LENT TO A COMPANY FOR INTEREST",
      "A CLOSE CONNECTION BETWEEN PEOPLE",
      "WHAT GLUE MAKES BETWEEN TWO SURFACES",
    ],
    candidates: [
      "STOCK",
      "FRIENDSHIP",
      "ADHESIVE",
      "LOAN",
      "BOND",
      "LINK",
      "SHARE",
      "TRUST",
      "CEMENT",
    ],
    tier: 3,
  },
  {
    word: "CHAIN",
    meanings: [
      "STORES OWNED UNDER ONE BRAND",
      "EVENTS THAT KEEP LEADING TO THE NEXT",
      "METAL LINKS FASTENED TOGETHER",
    ],
    candidates: [
      "FRANCHISE",
      "SEQUENCE",
      "ROPE",
      "RETAIL",
      "CHAIN",
      "SERIES",
      "CABLE",
      "NETWORK",
      "NECKLACE",
    ],
    tier: 2,
  },
  {
    word: "CLOUD",
    meanings: [
      "INTERNET STORAGE ON REMOTE SERVERS",
      "SOMETHING THAT CAN BLUR YOUR JUDGMENT",
      "WHITE OR GRAY MASS IN THE SKY",
    ],
    candidates: [
      "DRIVE",
      "FOG",
      "MIST",
      "DATABASE",
      "CLOUD",
      "BIAS",
      "BACKUP",
      "SMOKE",
      "HAZE",
    ],
    tier: 2,
  },
  {
    word: "CLUTCH",
    meanings: [
      "SMALL HANDLELESS HANDBAG",
      "GRAB AND HOLD TIGHTLY",
      "PEDAL USED WHEN CHANGING GEARS",
    ],
    candidates: [
      "PURSE",
      "GRIP",
      "BRAKE",
      "POUCH",
      "CLUTCH",
      "SQUEEZE",
      "ACCELERATOR",
      "SHIFT",
      "HANDBRAKE",
    ],
    tier: 2,
  },
  {
    word: "COLUMN",
    meanings: [
      "A FORMATION OF SOLDIERS OR VEHICLES",
      "NUMBERS ARRANGED VERTICALLY",
      "A TALL SUPPORT IN A BUILDING",
    ],
    candidates: [
      "RANK",
      "ROW",
      "BEAM",
      "CONVOY",
      "COLUMN",
      "LIST",
      "FILE",
      "GRID",
      "POST",
    ],
    tier: 3,
  },
  {
    word: "CONDITION",
    meanings: [
      "A REQUIREMENT BEFORE SOMETHING CAN HAPPEN",
      "TRAIN YOUR BODY FOR COMPETITION",
      "THE STATE SOMETHING IS IN",
    ],
    candidates: [
      "RULE",
      "PRACTICE",
      "SHAPE",
      "CLAUSE",
      "CONDITION",
      "FITNESS",
      "TERM",
      "STATUS",
      "FORM",
    ],
    tier: 3,
  },
  {
    word: "CRASH",
    meanings: [
      "SLEEP AT SOMEONE'S PLACE FOR THE NIGHT",
      "WHEN A COMPUTER SUDDENLY STOPS WORKING",
      "A VIOLENT COLLISION",
    ],
    candidates: [
      "COUCH",
      "FREEZE",
      "WRECK",
      "STAY",
      "CRASH",
      "GLITCH",
      "SHUTDOWN",
      "SMASH",
      "ACCIDENT",
    ],
    tier: 2,
  },
  {
    word: "FLIGHT",
    meanings: [
      "ESCAPE FROM DANGER OR PURSUIT",
      "A SET OF STAIRS BETWEEN FLOORS",
      "AN AIRPLANE JOURNEY",
    ],
    candidates: [
      "GETAWAY",
      "STEPS",
      "TRIP",
      "RETREAT",
      "FLIGHT",
      "LADDER",
      "TAKEOFF",
      "ROUTE",
      "DEPARTURE",
    ],
    tier: 2,
  },
  {
    word: "FLOAT",
    meanings: [
      "CASH KEPT IN A REGISTER FOR CHANGE",
      "DECORATED PLATFORM IN A PARADE",
      "STAYS ON THE SURFACE WITHOUT SINKING",
    ],
    candidates: [
      "TILL",
      "WAGON",
      "RAFT",
      "COINS",
      "FLOAT",
      "CART",
      "RESERVE",
      "BUOY",
      "BOAT",
    ],
    tier: 3,
  },
  {
    word: "HAIL",
    meanings: [
      "COME FROM A PARTICULAR HOMETOWN",
      "CALL A TAXI FROM THE CURB",
      "ICE PELLETS FALLING IN A STORM",
    ],
    candidates: [
      "ORIGINATE",
      "CAB",
      "SLEET",
      "SUMMON",
      "HAIL",
      "SNOW",
      "SIGNAL",
      "WAVE",
      "RAIN",
    ],
    tier: 2,
  },
  {
    word: "HEEL",
    meanings: [
      "COMMAND THAT MAKES A DOG WALK BESIDE YOU",
      "A DISHONORABLE OR MEAN PERSON",
      "BACK PART OF YOUR FOOT",
    ],
    candidates: [
      "SIT",
      "JERK",
      "ANKLE",
      "STAY",
      "HEEL",
      "CREEP",
      "TOE",
      "SOLE",
      "SHOE",
    ],
    tier: 2,
  },
];
