import { DailyWord } from './types';

export const DAILY_POOL: DailyWord[] = [
  {
    id: 'bark-1',
    answer: 'BARK',
    tier: 1,
    clues: ['A ship with three masts', "Pine and elm's armor", "Mailman's worst nightmare"],
    candidates: ['BARK', 'BITE', 'LOG', 'HOWL', 'SHIP', 'TREE'],
  },
  {
    id: 'ring-1',
    answer: 'RING',
    tier: 1,
    clues: ['Where fighters earn it', "Fourth finger's resident", 'What bells do best'],
    candidates: ['RING', 'BELL', 'BAND', 'ARENA', 'CIRCLE', 'CHIME'],
  },
  {
    id: 'match-1',
    answer: 'MATCH',
    tier: 1,
    clues: ['One scratch, instant light', 'Two things, one verdict', 'Where rivals settle things'],
    candidates: ['MATCH', 'GAME', 'LIGHTER', 'PAIR', 'FIGHT', 'SPARK'],
  },
  {
    id: 'spring-1',
    answer: 'SPRING',
    tier: 1,
    clues: ['Bouncy metal squiggle', 'Launched from a crouch', 'What snowmen dread most'],
    candidates: ['SPRING', 'JUMP', 'COIL', 'SEASON', 'WELL', 'CREEK'],
  },
  {
    id: 'pitch-1',
    answer: 'PITCH',
    tier: 1,
    clues: ["A note's altitude", 'Blacker than black itself', 'British grass, match-ready'],
    candidates: ['PITCH', 'TONE', 'TAR', 'FIELD', 'THROW', 'GRASS'],
  },
  {
    id: 'plant-1',
    answer: 'PLANT',
    tier: 1,
    clues: ['Nuclear factory floor', 'Mole in the crowd', 'Leaves need watering'],
    candidates: ['PLANT', 'SPY', 'FACTORY', 'FLOWER', 'MOLE', 'SEED'],
  },
  {
    id: 'charge-2',
    answer: 'CHARGE',
    tier: 2,
    clues: ['Left in your care', 'Head down, full speed', "Dead phone's problem"],
    candidates: ['CHARGE', 'DUTY', 'RUSH', 'BATTERY', 'PRICE', 'ATTACK'],
  },
  {
    id: 'bear-2',
    answer: 'BEAR',
    tier: 2,
    clues: ['The market that eats portfolios', 'Grit your teeth through it', 'Hibernates all winter'],
    candidates: ['BEAR', 'STOCK', 'ENDURE', 'BULL', 'ANIMAL', 'CARRY'],
  },
  {
    id: 'press-2',
    answer: 'PRESS',
    tier: 2,
    clues: ["Gutenberg's great machine", 'A wardrobe essential', 'Reporters as a group'],
    candidates: ['PRESS', 'IRON', 'PRINT', 'MEDIA', 'PUSH', 'NEWS'],
  },
  {
    id: 'bank-2',
    answer: 'BANK',
    tier: 2,
    clues: ['Sky tilted on purpose', 'What lighthouses argue with', "River's grassy edge"],
    candidates: ['BANK', 'TILT', 'FOG', 'SHORE', 'MONEY', 'RIVER'],
  },
  {
    id: 'table-2',
    answer: 'TABLE',
    tier: 2,
    clues: ['Underground water level', 'Numbers in columns', 'Elbows get judged here'],
    candidates: ['TABLE', 'CHART', 'WATER', 'DESK', 'DINNER', 'GRID'],
  },
  {
    id: 'draft-2',
    answer: 'DRAFT',
    tier: 2,
    clues: ["Pub's beer option", 'Cold sneaks under', 'First try, marked up'],
    candidates: ['DRAFT', 'BEER', 'BREEZE', 'SKETCH', 'VERSION', 'WIND'],
  },
  {
    id: 'cast-3',
    answer: 'CAST',
    tier: 3,
    clues: ['Friends sign the armor', 'Poured while still hot', 'Fishing line leaves hand'],
    candidates: ['CAST', 'CREW', 'MOLD', 'THROW', 'PLASTER', 'METAL'],
  },
  {
    id: 'sound-3',
    answer: 'SOUND',
    tier: 3,
    clues: ['Sleeping without stirring', 'Water between islands', 'Advice worth keeping'],
    candidates: ['SOUND', 'SLEEP', 'STRAIT', 'SOLID', 'ADVICE', 'CHANNEL'],
  },
  {
    id: 'strike-3',
    answer: 'STRIKE',
    tier: 3,
    clues: ['Idea hits suddenly', 'Workers walk out', 'Ten pins, one ball'],
    candidates: ['STRIKE', 'IDEA', 'PROTEST', 'BOWL', 'HIT', 'LIGHTNING'],
  },
  {
    id: 'draw-3',
    answer: 'DRAW',
    tier: 3,
    clues: ["Artist's first instinct", 'Fastest hand in the west', 'Neither side won'],
    candidates: ['DRAW', 'SKETCH', 'GUNSLINGER', 'TIE', 'PULL', 'LOTTERY'],
  },
  {
    id: 'ground-3',
    answer: 'GROUND',
    tier: 3,
    clues: ["Coffee's morning aftermath", 'Reason behind the belief', 'Plane stuck on earth'],
    candidates: ['GROUND', 'COFFEE', 'REASON', 'LAND', 'EARTH', 'BASE'],
  },
  {
    id: 'mean-3',
    answer: 'MEAN',
    tier: 3,
    clues: ['Middle of the numbers', 'Cruel without cause', 'Intends to do it'],
    candidates: ['MEAN', 'AVERAGE', 'CRUEL', 'INTEND', 'MIDDLE', 'PLAN'],
  },
];
