import { DailyWord } from './types';

export const DAILY_POOL: DailyWord[] = [
  {
    id: 'bark-1',
    answer: 'BARK',
    tier: 1,
    clues: ['A ship with three masts', "Pine and elm's armor", "Mailman's worst nightmare"],
    candidates: ['BARK', 'BITE', 'LOG', 'HOWL', 'SHIP', 'TREE'],
  },
  {
    id: 'ring-1',
    answer: 'RING',
    tier: 1,
    clues: ['Where fighters earn it', "Fourth finger's resident", 'What bells do best'],
    candidates: ['RING', 'BELL', 'BAND', 'ARENA', 'CIRCLE', 'CHIME'],
  },
  {
    id: 'match-1',
    answer: 'MATCH',
    tier: 1,
    clues: ['One scratch, instant light', 'Two things, one verdict', 'Where rivals settle things'],
    candidates: ['MATCH', 'GAME', 'LIGHTER', 'PAIR', 'FIGHT', 'SPARK'],
  },
  {
    id: 'spring-1',
    answer: 'SPRING',
    tier: 1,
    clues: ['Bouncy metal squiggle', 'Launched from a crouch', 'What snowmen dread most'],
    candidates: ['SPRING', 'JUMP', 'COIL', 'SEASON', 'WELL', 'CREEK'],
  },
  {
    id: 'pitch-1',
    answer: 'PITCH',
    tier: 1,
    clues: ["A note's altitude", 'Blacker than black itself', 'British grass, match-ready'],
    candidates: ['PITCH', 'TONE', 'TAR', 'FIELD', 'THROW', 'GRASS'],
  },
  {
    id: 'plant-1',
    answer: 'PLANT',
    tier: 1,
    clues: ['Nuclear factory floor', 'Mole in the crowd', 'Leaves need watering'],
    candidates: ['PLANT', 'SPY', 'FACTORY', 'FLOWER', 'MOLE', 'SEED'],
  },
  {
    id: 'charge-2',
    answer: 'CHARGE',
    tier: 2,
    clues: ['Left in your care', 'Head down, full speed', "Dead phone's problem"],
    candidates: ['CHARGE', 'DUTY', 'RUSH', 'BATTERY', 'PRICE', 'ATTACK'],
  },
  {
    id: 'bear-2',
    answer: 'BEAR',
    tier: 2,
    clues: ['The market that eats portfolios', 'Grit your teeth through it', 'Hibernates all winter'],
    candidates: ['BEAR', 'STOCK', 'ENDURE', 'BULL', 'ANIMAL', 'CARRY'],
  },
  {
    id: 'press-2',
    answer: 'PRESS',
    tier: 2,
    clues: ["Gutenberg's great machine", 'A wardrobe essential', 'Reporters as a group'],
    candidates: ['PRESS', 'IRON', 'PRINT', 'MEDIA', 'PUSH', 'NEWS'],
  },
  {
    id: 'bank-2',
    answer: 'BANK',
    tier: 2,
    clues: ['Sky tilted on purpose', 'What lighthouses argue with', "River's grassy edge"],
    candidates: ['BANK', 'TILT', 'FOG', 'SHORE', 'MONEY', 'RIVER'],
  },
  {
    id: 'table-2',
    answer: 'TABLE',
    tier: 2,
    clues: ['Underground water level', 'Numbers in columns', 'Elbows get judged here'],
    candidates: ['TABLE', 'CHART', 'WATER', 'DESK', 'DINNER', 'GRID'],
  },
  {
    id: 'draft-2',
    answer: 'DRAFT',
    tier: 2,
    clues: ["Pub's beer option", 'Cold sneaks under', 'First try, marked up'],
    candidates: ['DRAFT', 'BEER', 'BREEZE', 'SKETCH', 'VERSION', 'WIND'],
  },
  {
    id: 'cast-3',
    answer: 'CAST',
    tier: 3,
    clues: ['Friends sign the armor', 'Poured while still hot', 'Fishing line leaves hand'],
    candidates: ['CAST', 'CREW', 'MOLD', 'THROW', 'PLASTER', 'METAL'],
  },
  {
    id: 'sound-3',
    answer: 'SOUND',
    tier: 3,
    clues: ['Sleeping without stirring', 'Water between islands', 'Advice worth keeping'],
    candidates: ['SOUND', 'SLEEP', 'STRAIT', 'SOLID', 'ADVICE', 'CHANNEL'],
  },
  {
    id: 'strike-3',
    answer: 'STRIKE',
    tier: 3,
    clues: ['Idea hits suddenly', 'Workers walk out', 'Ten pins, one ball'],
    candidates: ['STRIKE', 'IDEA', 'PROTEST', 'BOWL', 'HIT', 'LIGHTNING'],
  },
  {
    id: 'draw-3',
    answer: 'DRAW',
    tier: 3,
    clues: ["Artist's first instinct", 'Fastest hand in the west', 'Neither side won'],
    candidates: ['DRAW', 'SKETCH', 'GUNSLINGER', 'TIE', 'PULL', 'LOTTERY'],
  },
  {
    id: 'ground-3',
    answer: 'GROUND',
    tier: 3,
    clues: ["Coffee's morning aftermath", 'Reason behind the belief', 'Plane stuck on earth'],
    candidates: ['GROUND', 'COFFEE', 'REASON', 'LAND', 'EARTH', 'BASE'],
  },
  {
    id: 'mean-3',
    answer: 'MEAN',
    tier: 3,
    clues: ['Middle of the numbers', 'Cruel without cause', 'Intends to do it'],
    candidates: ['MEAN', 'AVERAGE', 'CRUEL', 'INTEND', 'MIDDLE', 'PLAN'],
  },

  // ── 2026-07-13 pool expansion (drafts, pending joint content pass) ──

  {
    id: 'bat-1',
    answer: 'BAT',
    tier: 1,
    clues: ['Cave sleeper, hangs upside down', 'Swings for the fences', 'One flutter of the lashes'],
    candidates: ['BAT', 'CAVE', 'CLUB', 'WINK', 'BALL', 'GLOVE'],
  },
  {
    id: 'star-1',
    answer: 'STAR',
    tier: 1,
    clues: ['Twinkles after dark', 'Name above the movie title', "Sheriff's badge shape"],
    candidates: ['STAR', 'SUN', 'ACTOR', 'BADGE', 'SKY', 'FAME'],
  },
  {
    id: 'box-1',
    answer: 'BOX',
    tier: 1,
    clues: ['Cardboard with flaps', 'Gloves up, twelve rounds', 'Check it to agree'],
    candidates: ['BOX', 'CRATE', 'RING', 'FORM', 'GLOVE', 'TAPE'],
  },
  {
    id: 'wave-1',
    answer: 'WAVE',
    tier: 1,
    clues: ["Ocean's repeating delivery", 'Goodbye without words', "Heat that won't quit for a week"],
    candidates: ['WAVE', 'TIDE', 'SALUTE', 'SURF', 'HEAT', 'SWELL'],
  },
  {
    id: 'nail-1',
    answer: 'NAIL',
    tier: 1,
    clues: ["Hammer's best friend", 'Polish dries on ten of them', 'Aced it completely'],
    candidates: ['NAIL', 'HAMMER', 'SCREW', 'POLISH', 'FINGER', 'WIN'],
  },
  {
    id: 'letter-1',
    answer: 'LETTER',
    tier: 1,
    clues: ["Envelope's cargo", 'Twenty-six to choose from', "Varsity jacket's badge"],
    candidates: ['LETTER', 'STAMP', 'ALPHABET', 'MAIL', 'WORD', 'PATCH'],
  },
  {
    id: 'train-1',
    answer: 'TRAIN',
    tier: 1,
    clues: ['Rides the rails', 'Practice until perfect', 'Wedding dress drags it'],
    candidates: ['TRAIN', 'TRACK', 'COACH', 'GOWN', 'DRILL', 'RAIL'],
  },
  {
    id: 'fall-1',
    answer: 'FALL',
    tier: 1,
    clues: ['Leaves change color', 'Gravity wins again', 'Empires do it eventually'],
    candidates: ['FALL', 'AUTUMN', 'TRIP', 'LEAVES', 'COLLAPSE', 'SLIP'],
  },
  {
    id: 'park-1',
    answer: 'PARK',
    tier: 1,
    clues: ['Swings and slides', 'Leave it between the lines', 'Rangers guard the big one'],
    candidates: ['PARK', 'SWING', 'GARAGE', 'FOREST', 'LOT', 'FIELD'],
  },
  {
    id: 'light-1',
    answer: 'LIGHT',
    tier: 1,
    clues: ['Switch flips it on', 'Barely weighs a thing', 'A match offers one'],
    candidates: ['LIGHT', 'LAMP', 'FEATHER', 'FLAME', 'BULB', 'GLOW'],
  },
  {
    id: 'cold-1',
    answer: 'COLD',
    tier: 1,
    clues: ['Sweater weather and then some', 'Sniffles and a red nose', 'Shoulder treatment for exes'],
    candidates: ['COLD', 'FREEZE', 'FLU', 'ICE', 'SNUB', 'CHILL'],
  },
  {
    id: 'band-1',
    answer: 'BAND',
    tier: 1,
    clues: ['Garage practice, big dreams', 'Rubber loop around everything', 'Ring without the rock'],
    candidates: ['BAND', 'GROUP', 'RUBBER', 'RING', 'STRAP', 'CREW'],
  },

  {
    id: 'toast-2',
    answer: 'TOAST',
    tier: 2,
    clues: ['Breakfast gone crispy', 'Glasses raised high', 'Completely done for'],
    candidates: ['TOAST', 'BREAD', 'CHEERS', 'BUTTER', 'SPEECH', 'DONE'],
  },
  {
    id: 'crown-2',
    answer: 'CROWN',
    tier: 2,
    clues: ['Royal headgear', "Dentist's porcelain cap", 'Where the tree meets sky'],
    candidates: ['CROWN', 'KING', 'TOOTH', 'TIARA', 'TOP', 'ROOT'],
  },
  {
    id: 'scale-2',
    answer: 'SCALE',
    tier: 2,
    clues: ['Bathroom truth-teller', 'Fish wear thousands', 'Do-re-mi ladder'],
    candidates: ['SCALE', 'WEIGHT', 'FISH', 'PIANO', 'SKIN', 'MAP'],
  },
  {
    id: 'bolt-2',
    answer: 'BOLT',
    tier: 2,
    clues: ["Lightning's signature", "Nut's other half", 'Out the door at full speed'],
    candidates: ['BOLT', 'FLASH', 'SCREW', 'RUN', 'LOCK', 'NUT'],
  },
  {
    id: 'season-2',
    answer: 'SEASON',
    tier: 2,
    clues: ['Four per year', 'Salt and pepper it', 'Ten episodes, one arc'],
    candidates: ['SEASON', 'WINTER', 'SPICE', 'EPISODE', 'SERIES', 'FLAVOR'],
  },
  {
    id: 'run-2',
    answer: 'RUN',
    tier: 2,
    clues: ['Morning miles before work', "Stocking's spreading disaster", "Theater show's whole stretch"],
    candidates: ['RUN', 'JOG', 'TEAR', 'SHOW', 'RACE', 'SPRINT'],
  },
  {
    id: 'note-2',
    answer: 'NOTE',
    tier: 2,
    clues: ['Sticky reminder on the fridge', 'One beat of the melody', "Twenty with Jackson's face"],
    candidates: ['NOTE', 'MEMO', 'TUNE', 'BILL', 'LETTER', 'CHORD'],
  },
  {
    id: 'tip-2',
    answer: 'TIP',
    tier: 2,
    clues: ['Twenty percent for service', "Iceberg's visible bit", 'Insider whisper'],
    candidates: ['TIP', 'WAITER', 'PEAK', 'HINT', 'CASH', 'EDGE'],
  },
  {
    id: 'trunk-2',
    answer: 'TRUNK',
    tier: 2,
    clues: ["Elephant's fifth limb", 'Spare tire lives here', 'Attic chest of heirlooms'],
    candidates: ['TRUNK', 'NOSE', 'CAR', 'CHEST', 'BRANCH', 'CASE'],
  },
  {
    id: 'racket-2',
    answer: 'RACKET',
    tier: 2,
    clues: ['Strung for the serve', 'Noise the neighbors report', 'Con with a system'],
    candidates: ['RACKET', 'PADDLE', 'NOISE', 'SCHEME', 'BAT', 'COURT'],
  },
  {
    id: 'suit-2',
    answer: 'SUIT',
    tier: 2,
    clues: ['Tailored for the interview', 'One of four in every deck', 'Lawyer files one'],
    candidates: ['SUIT', 'TUX', 'HEARTS', 'CASE', 'TIE', 'DECK'],
  },
  {
    id: 'pool-2',
    answer: 'POOL',
    tier: 2,
    clues: ["Cannonball's landing zone", 'Everyone chips in', 'Eight ball, corner pocket'],
    candidates: ['POOL', 'DIVE', 'FUND', 'CUE', 'POND', 'KITTY'],
  },

  {
    id: 'husky-3',
    answer: 'HUSKY',
    tier: 3,
    clues: ["Sled team's engine", 'Voice after the concert', 'Big for his age, says grandma'],
    candidates: ['HUSKY', 'HOARSE', 'BURLY', 'WOLF', 'SLED', 'GRAVEL'],
  },
  {
    id: 'lap-3',
    answer: 'LAP',
    tier: 3,
    clues: ["Cat's favorite landing spot", 'Once around the track', 'Waves against the hull do it'],
    candidates: ['LAP', 'KNEE', 'CIRCUIT', 'SPLASH', 'SEAT', 'ROUND'],
  },
  {
    id: 'seal-3',
    answer: 'SEAL',
    tier: 3,
    clues: ["Harbor's whiskered clown", 'Wax pressed on royal mail', 'Airtight guarantee'],
    candidates: ['SEAL', 'OTTER', 'WAX', 'STAMP', 'LOCK', 'WALRUS'],
  },
  {
    id: 'mint-3',
    answer: 'MINT',
    tier: 3,
    clues: ["Toothpaste's signature flavor", 'Where money is literally made', "Collector's dream condition"],
    candidates: ['MINT', 'GUM', 'TREASURY', 'PRISTINE', 'COIN', 'LEAF'],
  },
  {
    id: 'hatch-3',
    answer: 'HATCH',
    tier: 3,
    clues: ["Chick's grand exit", "Submarine's only entrance", 'Scheme takes shape in secret'],
    candidates: ['HATCH', 'EGG', 'DOOR', 'PLOT', 'LID', 'NEST'],
  },
  {
    id: 'grain-3',
    answer: 'GRAIN',
    tier: 3,
    clues: ["Silo's golden cargo", "Wood's natural flow", 'Skeptics take one of salt'],
    candidates: ['GRAIN', 'WHEAT', 'TEXTURE', 'SALT', 'SAND', 'RICE'],
  },
  {
    id: 'vault-3',
    answer: 'VAULT',
    tier: 3,
    clues: ["Bank's steel fortress", "Gymnast's flying moment", "Cathedral ceiling's curve"],
    candidates: ['VAULT', 'SAFE', 'LEAP', 'ARCH', 'TOMB', 'GYM'],
  },
  {
    id: 'tender-3',
    answer: 'TENDER',
    tier: 3,
    clues: ['Fork slides right through', 'Legal kind pays debts', 'Sore wherever you poke it'],
    candidates: ['TENDER', 'SORE', 'CASH', 'GENTLE', 'OFFER', 'SOFT'],
  },
  {
    id: 'patent-3',
    answer: 'PATENT',
    tier: 3,
    clues: ["Inventor's legal moat", 'Shiny shoes wear it', 'Nonsense of the clearest kind'],
    candidates: ['PATENT', 'INVENTION', 'GLOSS', 'OBVIOUS', 'LICENSE', 'LEATHER'],
  },
  {
    id: 'rash-3',
    answer: 'RASH',
    tier: 3,
    clues: ["Poison ivy's parting gift", 'Decision that skipped the thinking', 'String of car break-ins'],
    candidates: ['RASH', 'HIVES', 'HASTY', 'SPREE', 'ITCH', 'IMPULSE'],
  },
  {
    id: 'graft-3',
    answer: 'GRAFT',
    tier: 3,
    clues: ['Burn victims need one', "City hall's dirty money", 'Two branches become one'],
    candidates: ['GRAFT', 'BRIBE', 'SPLICE', 'SKIN', 'SCANDAL', 'PRUNE'],
  },
  {
    id: 'cardinal-3',
    answer: 'CARDINAL',
    tier: 3,
    clues: ['Red flash at the feeder', "Rome's scarlet electors", 'North is one of four'],
    candidates: ['CARDINAL', 'ROBIN', 'BISHOP', 'COMPASS', 'POPE', 'CRIMSON'],
  },
];
