export const POLLY_LINES = {
  // Relationship-memory dialogue. These lines fire only when the relationship
  // brain proves the corresponding history; ordinary gameplay keeps its own pools.
  relComeback01: 'I WAS GETTING USED TO YOU LOSING.',
  relComeback02: 'WHERE’S THAT BEEN HIDING?',
  relComeback03: 'OH. SO YOU DO REMEMBER HOW.',
  relComeback04: 'THERE YOU ARE.',
  relComeback05: 'I THOUGHT YOU’D LOST THAT.',
  relComeback06: 'WELL, THAT LOOKED FAMILIAR.',
  relComeback07: 'I LIKED YOU BETTER LAST TIME.',
  relComeback08: 'I WAS STARTING TO FEEL SAFE.',
  relComeback09: 'THAT WASN’T THE YOU I’VE BEEN BEATING.',
  relComeback10: 'DON’T START DOING THAT AGAIN.',
  relComeback11: 'ONE GOOD HUNT. DON’T GET EXCITED.',
  relComeback12: 'I KNEW YOU’D WAKE UP EVENTUALLY.',
  relComeback13: 'AND HERE I THOUGHT YOU WERE DONE.',
  relComeback14: 'THERE’S THE PROBLEM I REMEMBER.',
  relComeback15: 'I WAS ENJOYING YOUR LITTLE SLUMP.',
  relComeback16: 'SO THE BRAIN DAMAGE WASN’T PERMANENT.',
  relComeback17: 'YOU CAN WIN AND STILL BE A LOSER.',
  relComeback18: 'LOOKS LIKE ME AND YOU ARE GONNA HAVE A PROBLEM.',
  relVeteranSlump01: 'WHAT HAPPENED TO YOU?',
  relVeteranSlump02: 'YOU USED TO BE A PROBLEM.',
  relVeteranSlump03: 'I REMEMBER WHEN YOU WERE GOOD AT THIS.',
  relVeteranSlump04: 'THIS ISN’T THE PLAYER I REMEMBER.',
  relVeteranSlump05: 'YOU’RE MAKING THIS WAY TOO EASY.',
  relVeteranSlump06: 'I ALMOST MISS THE OLD YOU.',
  relVeteranSlump07: 'WHERE’D ALL THAT CONFIDENCE GO?',
  relVeteranSlump08: 'YOU WERE SCARIER BEFORE.',
  relVeteranSlump09: 'THIS IS GETTING A LITTLE SAD.',
  relVeteranSlump10: 'I’VE SEEN YOU DO BETTER. MUCH BETTER.',
  relVeteranSlump11: 'REMEMBER WHEN I HAD TO TRY?',
  relVeteranSlump12: 'I WAS WONDERING WHEN YOU’D GET WORSE.',
  relVeteranSlump13: 'KEEP THIS UP AND I MIGHT START FEELING BAD.',
  relVeteranSlump14: 'I THINK YOUR BEST DAYS ARE BEHIND YOU.',
  relVeteranSlump15: 'YOU’RE REALLY MAKING ME MISS THE COMPETITION.',
  relVeteranSlump16: 'DID SOMEBODY ELSE START PLAYING FOR YOU?',
  relVeteranSlump17: 'I KNOW YOU CAN DO BETTER. THAT’S WHAT MAKES THIS FUNNY.',
  relVeteranSlump18: 'DON’T WORRY. I REMEMBER WHEN YOU WERE DANGEROUS.',
  relVeteranSlump19: 'YOU SHOULD PROBABLY GET TESTED FOR BRAIN DAMAGE.',
  relVeteranSlump20: 'WHO’S PLAYING FOR YOU?',
  relVeteranSlump21: 'DID YOU LET SOMEBODY ELSE PLAY FOR YOU?',
  relVeteranSlump22: 'IS SOMEBODY ELSE PLAYING UNDER YOUR NAME?',
  relVeteranSlump23: 'DID YOU LET YOUR LITTLE BROTHER PLAY?',
  relVeteranSlump24: 'DID YOU GIVE YOUR PHONE TO A FIVE-YEAR-OLD?',
  relVeteranSlump25: 'WHOEVER’S PLAYING FOR YOU, TELL THEM TO STOP.',
  relVeteranSlump26: 'GIVE THE PHONE BACK TO WHOEVER WAS PLAYING BEFORE.',
  relVeteranSlump27: 'ARE YOU SURE THIS IS STILL YOU?',
  relVeteranSlump28: 'I’M GONNA NEED SOME PROOF THIS IS ACTUALLY YOU.',
  relVeteranSlump29: 'DID SOMEONE STEAL YOUR PHONE AND START PLAYING?',
  relVeteranSlump30: 'NO WAY THIS IS YOU. SHOW ME YOUR ID.',
  relReturn01: 'MISS ME?',
  relReturn02: 'BACK AGAIN?',
  relReturn03: 'LOOK WHO DECIDED TO COME BACK.',
  relReturn04: 'I WAS WONDERING WHERE YOU WENT.',
  relReturn05: 'TOOK YOU LONG ENOUGH.',
  relReturn06: 'I THOUGHT YOU QUIT.',
  relReturn07: 'I THOUGHT I FINALLY GOT RID OF YOU.',
  relReturn08: 'AND HERE I WAS ENJOYING THE PEACE AND QUIET.',
  relReturn09: 'DON’T WORRY. I BARELY NOTICED YOU WERE GONE.',
  relReturn10: 'I DIDN’T MISS YOU, IF THAT’S WHAT YOU’RE THINKING.',
  relReturn11: 'WHO SAID YOU COULD COME BACK?',
  relReturn12: 'YOU DO REMEMBER HOW THIS WORKS, RIGHT?',
  relReturn13: 'NEED ME TO EXPLAIN THE RULES AGAIN?',
  relReturn14: 'LET’S SEE WHAT YOU FORGOT.',
  relReturn15: 'HOPE YOU DIDN’T FORGET EVERYTHING.',
  relReturn16: 'LET’S SEE IF THE TIME OFF HELPED.',
  relReturn17: 'YOU LOOK RUSTY ALREADY.',
  relReturn18: 'I’VE HAD PLENTY OF TIME TO COME UP WITH NEW TRAPS.',
  relReturn19: 'I’VE BEEN PRACTICING. HAVE YOU?',
  relReturn20: 'YOU LEFT ME ALONE WITH ALL THESE WORDS.',
  relReturn21: 'DO YOU HAVE ANY IDEA HOW BORING IT GETS WITHOUT SOMEONE TO BEAT?',
  relReturn22: 'I ALMOST HAD TO FIND SOMEBODY ELSE TO ANNOY.',
  relReturn23: 'I WAS THIS CLOSE TO REPLACING YOU.',
  relReturn24: 'YOUR REPLACEMENT DIDN’T WORK OUT.',
  relReturn25: 'I KEPT YOUR SPOT. BY ACCIDENT.',
  relReturn26: 'YOUR SPOT’S STILL HERE. DON’T READ INTO IT.',
  relReturn27: 'I KNEW YOU’D COME CRAWLING BACK.',
  relReturn28: 'COULDN’T STAY AWAY, COULD YOU?',
  relReturn29: 'WHAT, DID YOU RUN OUT OF OTHER GAMES?',
  relReturn30: 'SO WE’RE DOING THIS AGAIN.',
  relReturn31: 'I WAS HAVING SUCH A NICE WEEK.',
  relReturn32: 'THERE GOES THE NEIGHBORHOOD.',
  relReturn33: 'WELL, THE VACATION’S OVER.',
  relReturn34: 'I SEE YOU FOUND YOUR WAY BACK.',
  relReturn35: 'YOU AGAIN. I SHOULD’VE CHANGED THE LOCKS.',
  relReturn36: 'I REALLY NEED TO START LOCKING THE DOOR.',
  relReturn37: 'DIDN’T WE GET RID OF YOU?',
  relReturn38: 'I WAS JUST STARTING TO FORGET YOUR FACE.',
  relReturn39: 'SORRY, DO I KNOW YOU?',
  relReturn40: 'REMIND ME. WERE YOU ANY GOOD AT THIS?',
  relReturn41: 'I FORGOT. ARE YOU THE ONE WHO LOSES A LOT?',
  relReturn42: 'WAIT. I KNOW THAT FACE.',
  relReturn43: 'I KNEW THE QUIET WOULDN’T LAST.',
  relReturn44: 'YOU COULD’VE AT LEAST CALLED.',
  relReturn45: 'NO NOTE? NO GOODBYE? NOTHING?',
  relReturn46: 'NICE OF YOU TO REMEMBER I EXIST.',
  relReturn47: 'I’M NOT MAD. I JUST EXPECTED BETTER.',
  relReturn48: 'ABANDONMENT ISSUES? ME? NEVER.',
  relReturn49: 'DON’T MAKE A BIG DEAL OUT OF IT. I KNEW YOU’D BE BACK.',
  relReturn50: 'WHAT, YOU LOSE YOUR PHONE?',
  relReturn51: 'SOMEBODY STEAL YOUR PHONE?',
  relReturn52: 'FINALLY GOT YOUR PHONE BACK?',
  relReturn53: 'FINALLY GOT YOUR PHONE TURNED BACK ON?',
  relReturn54: 'WHAT HAPPENED? FORGET YOUR PASSWORD?',
  relReturn55: 'LET ME GUESS. YOU LOST YOUR CHARGER.',
  relReturn56: 'PHONE FINALLY COME BACK FROM THE DEAD?',
  relReturn57: 'WHAT, NO WI-FI FOR A WEEK?',
  relReturn58: 'DID YOU DROP YOUR PHONE IN THE TOILET OR SOMETHING?',
  relReturn59: 'SO WHO HAD YOUR PHONE THIS WHOLE TIME?',
  relReturn60: 'FINALLY REMEMBERED WHERE YOU LEFT YOUR PHONE?',
  relReturn61: 'I WAS ABOUT TO REPORT YOUR PHONE MISSING.',
  relHauntRematch01: 'LOOK WHO’S BACK TO HAUNT YOU.',
  relHauntRematch02: 'REMEMBER THIS ONE?',
  relHauntRematch03: 'I KNOW YOU REMEMBER THIS ONE.',
  relHauntRematch04: 'OH, YOU TWO KNOW EACH OTHER.',
  relHauntRematch05: 'WELL, THIS SHOULD LOOK FAMILIAR.',
  relHauntRematch06: 'GUESS WHO’S BACK.',
  relHauntRematch07: 'I’VE BEEN SAVING THIS ONE FOR YOU.',
  relHauntRematch08: 'I WAS HOPING YOU’D GET THIS ONE AGAIN.',
  relHauntRematch09: 'THIS ONE REMEMBERS YOU TOO.',
  relHauntRematch10: 'YOU NEVER DID SETTLE THIS, DID YOU?',
  relHauntRematch11: 'YOU’VE GOT SOME UNFINISHED BUSINESS HERE.',
  relHauntRematch12: 'SECOND CHANCES ARE ADORABLE.',
  relHauntRematch13: 'READY TO MAKE THE SAME MISTAKE TWICE?',
  relHauntRematch14: 'LET’S SEE IF YOU LEARNED ANYTHING.',
  relHauntRematch15: 'MAYBE IT’LL GO EASY ON YOU THIS TIME.',
  relHauntRematch16: 'I WOULDN’T COUNT ON IT.',
  relHauntRematch17: 'YOU COULDN’T HANDLE THIS ONE LAST TIME.',
  relHauntRematch18: 'THIS DIDN’T GO SO WELL FOR YOU BEFORE.',
  relHauntRematch19: 'LAST TIME WAS FUN. FOR ME.',
  relHauntRematch20: 'I REMEMBER WHAT HAPPENED LAST TIME.',
  relHauntRematch21: 'DON’T WORRY. I WON’T TELL THEM WHAT HAPPENED LAST TIME.',
  relHauntRematch22: 'ACT LIKE YOU HAVEN’T SEEN IT BEFORE.',
  relHauntRematch23: 'TRY NOT TO EMBARRASS YOURSELF AGAIN.',
  relHauntRematch24: 'YOU WANT ANOTHER SHOT AT THIS ONE?',
  relHauntRematch25: 'HERE’S YOUR CHANCE TO FIX THAT LITTLE MISTAKE.',
  relHauntRematch26: 'I’M SURE IT WAS JUST BAD LUCK LAST TIME.',
  relHauntRematch27: 'YOU’VE HAD PLENTY OF TIME TO THINK ABOUT THIS ONE.',
  relHauntRematch28: 'NO EXCUSES THIS TIME.',
  relHauntRematch29: 'SAME WORD. SAME YOU. LET’S SEE.',
  relHauntRematch30: 'ROUND TWO. TRY TO LAST LONGER.',
  relHauntRematch31: 'REVENGE OR REPEAT?',
  relHauntRematch32: 'LET’S SEE IF THIS STORY ENDS DIFFERENTLY.',
  relHauntRematch33: 'HERE WE GO AGAIN.',
  relHauntRematch34: 'BACK FOR ANOTHER BEATING?',
  relHauntRematch35: 'YOU SURE YOU WANT TO DO THIS AGAIN?',
  relHauntRematch36: 'I’D BE NERVOUS TOO.',
  relHauntRematch37: 'DON’T LOOK AT ME. YOU’RE THE ONE WHO LOST TO IT.',
  relHauntRematch38: 'I DIDN’T PICK IT. IT PICKED YOU.',
  relHauntRematch39: 'IT ASKED FOR YOU BY NAME.',
  relHauntRematch40: 'IT SAID IT MISSED YOU.',
  relHauntRematch41: 'YOUR OLD FRIEND CAME BACK.',
  relHauntRematch42: 'YOUR FAVORITE WORD IS BACK.',
  relHauntRematch43: 'I THINK IT LIKES YOU.',
  relHauntRematch44: 'YOU TWO REALLY NEED TO WORK THIS OUT.',
  relHauntRematch45: 'I’LL GIVE YOU TWO SOME PRIVACY.',
  relHauntRematch46: 'AW. IT REMEMBERED YOU.',
  relHauntRematch47: 'I TOLD IT YOU’D BE BACK.',
  relHauntRematch48: 'IT DIDN’T BELIEVE YOU’D COME BACK FOR MORE.',
  relHauntRematch49: 'I THINK IT WANTS A REMATCH.',
  relHauntRematch50: 'IT BEAT YOU ONCE. NOW IT’S GETTING COCKY.',
  relHauntRematch51: 'DON’T LET IT BEAT YOU TWICE. THAT’D BE EMBARRASSING.',
  relHauntRematch52: 'LOSE TO THIS AGAIN AND I’M NEVER LETTING YOU FORGET IT.',
  relHauntRematch53: 'IF THIS BEATS YOU AGAIN, IT’S OFFICIALLY PERSONAL.',
  relHauntRematch54: 'AT SOME POINT YOU’RE GONNA HAVE TO BEAT THIS THING.',
  relHauntRematch55: 'HOW MANY TIMES DO YOU PLAN ON LOSING TO THIS ONE?',
  relHauntRematch56: 'YOU KNOW IT GETS FUNNIER EVERY TIME, RIGHT?',
  relHauntRematch57: 'I’M STARTING TO THINK THIS WORD OWNS YOU.',
  relHauntRematch58: 'THIS WORD HAS A BETTER RECORD AGAINST YOU THAN I DO.',
  relHauntRematch59: 'I’M ROOTING FOR THE WORD. OBVIOUSLY.',
  relHauntRematch60: 'I PUT MY MONEY ON THE WORD.',
  relHauntRematch61: 'DON’T MAKE ME REGRET BETTING AGAINST YOU.',
  relHauntRematch62: 'ACTUALLY, DO. THIS IS ENTERTAINING.',
  relHauntRematch63: 'YOU’VE BEEN THINKING ABOUT THIS ONE, HAVEN’T YOU?',
  relHauntRematch64: 'BET YOU THOUGHT YOU’D SEEN THE LAST OF THIS ONE.',
  relHauntRematch65: 'SOME WORDS JUST WON’T STAY DEAD.',
  relHauntRematch66: 'YOU LEFT THIS ONE UNFINISHED.',
  relHauntRematch67: 'TIME TO FINISH WHAT YOU STARTED.',
  relHauntRematch68: 'THIS ONE’S STILL GOT YOUR NAME ON IT.',
  relHauntRematch69: 'THERE’S THAT WORD YOU COULDN’T BEAT.',
  relHauntRematch70: 'OH, THIS ONE. I REMEMBER THIS.',
  relHauntRematch71: 'KABOOM, LOOK WHO’S BACK IN THE ROOM.',
  homeBackAgain: 'Back again?',
  homeMissMe: 'Miss me?',
  homeYourHighness: 'The name’s Polly. But you may call me Your Highness.',
  homeChamp: 'The champ is here. Me. I’m the champ.',
  homeCracker: 'And no, I don’t want a cracker.',
  homeGoAgain: 'Let’s go again.',
  homeReady: 'Are you ready? Because I’m ready.',
  homeDoubleOrNothing: 'Double or nothing.',
  homeCrown: 'I see you eyeing my crown.',
  homeFirstMeeting: 'Who are you? What do you want?',
  bossCage: 'I was still in the cage when I learned that one.',
  bossForYou: 'This one’s for you.',
  bossWaiting: 'I’ve been waiting to use this.',
  bossFavorite: 'Here we go. My favorite.',
  bossPutWork: 'I put work into this one.',
  huntLaugh: 'BBBLAAAAHHAHAHA!',
  huntCleanSweep: "Bet you can't do that again.",
  huntThoughtSo: 'Thought so.',
  huntGotcha: 'Gotcha.',
  huntThereItIs: 'There it is.',
  huntEveryTime: 'Every time.',
  huntStillWorks: 'Still works.',
  huntAllMe: 'That’s all me.',
  huntGoodIsntIt: 'Good, isn’t it.',
  huntLoveThisGame: 'I love this game.',
  huntMyHouse: 'This is MY house.',
  huntWalkedRightIn: 'Walked right into that one.',
  huntGotMeCrowned: 'That one got me crowned.',
  huntZing: 'Zing!',
  huntStreakSoWhat: 'So what.',
  huntStreakEasy: 'Those were easy.',
  huntStreakWhosCounting: 'But who’s counting?',
  huntStreakLetYouHave: 'I let you have those.',
  huntStreakWarmUp: 'That was the warm-up.',
  huntStreakPacing: 'I’m pacing myself.',
  streakLucky: 'Lucky.',
  streakYikes: 'YIKES!',
  streakNotOver: 'The Hunt isn’t over yet.',
  streakStillGetYa: 'I’m still gonna get ya.',
  streakBirdBrain: 'Bird brain. Me, I mean.',
  streakRuffling: 'You’re ruffling my feathers.',
  huntHesitation: 'YES... NO... MAYBE SO...',
  huntAreYouSure: 'Are you sure?',
  huntRemember: 'Remember me.',
  resultsNobodySaw: 'Nobody saw that.',
  resultsNeverHappened: 'That never happened.',
  resultsAMoment: 'I’d like a moment.',
  resultsRude: 'Well. That was rude.',
  resultsDareYou: 'Do that again. I dare you.',
  resultsThatWasGood: 'Fine. That one was good.',
  resultsReadEveryOne: 'Every trap. You read every one.',
  resultsNothingToSay: 'I have nothing to say to you.',
  resultsIWroteThose: 'I wrote all of those, you know.',
  resultsTakingNotes: 'Take the night. I’m taking notes.',
  resultsGettingOld: 'This is getting old.',
  resultsEnjoyIt: 'Enjoy it while it lasts.',
  resultsAdjustments: 'I’m making adjustments.',
  resultsDontGetComfortable: 'Don’t get comfortable.',
  resultsNewOnesTonight: 'I’m writing new ones tonight.',
  resultsLuckyLately: 'You’ve been lucky a lot lately.',
  resultsIveNoticed: 'I’ve noticed. Obviously I’ve noticed.',
  resultsManyMore: 'There’s many more to come.',
  resultsSecondBest: 'That was my second best.',
  resultsGotOne: 'One. You got one.',
  dailyButterKnife: 'Sharp as a butter knife.',
  dailyLossBat: 'CAN’T BEAT THAT WITH A BAT.',
  dailyWinTomorrow: 'WON’T HAPPEN TOMORROW.',
  // Daily per-round reaction pool, keyed to the rivalry state (BookRivalryState)
  // read from Hunt. See DAILY_MOOD_LINES in pwDailyMaterials.ts.
  dailyDismissiveInk: 'Barely worth the ink.',
  dailyDismissiveMovingOn: 'Hm. Moving on.',
  dailyDismissiveWhoAreYou: 'Who are you again?',
  dailyDismissiveWhateverThatWas: 'Fine. Whatever that was.',
  dailyAmusedDoItAgain: 'Charming. Do it again.',
  dailyAmusedArrangement: 'I do enjoy this arrangement.',
  dailyAmusedPredictable: 'Predictable. I like predictable.',
  dailyAmusedKnewIt: 'I knew you were gonna pick that one.',
  dailyAmusedComeBack: 'Come back. I’m here every day.',
  dailyWatchfulFaster: 'Faster than yesterday.',
  dailyWatchfulThatsNew: 'Hm. That’s new.',
  dailyWatchfulCoincidence: 'Coincidence, probably.',
  dailyWatchfulWatchingThis: 'Watching this one.',
  dailyWatchfulGoldFeather: 'Must want that gold feather.',
  dailyRattledLetYouHave: 'I let you have that one.',
  dailyRattledBadLight: 'Bad light. Not my fault.',
  dailyRattledLuck: 'Luck. Still luck, though.',
  dailyRattledShouldntCount: 'That shouldn’t count.',
  dailyRattledReallyHappening: 'Is this really happening right now?',
  dailyConcedingNewTraps: 'New traps. Starting tomorrow.',
  dailyConcedingOutOfExcuses: 'I’m out of excuses. Hate that.',
  dailyConcedingNothingHolding: 'Nothing’s holding today.',
  dailyConcedingDrawingBoard: 'Back to the drawing board. Apparently.',
  dailyConcedingNooo: 'Nooooo',
  huntIntro: 'Enter the Hunt. We’ll see who hunts who.',
  huntHauntIntro: 'I hunt you. I haunt you.',
  huntAbandonTaunt: 'See you later, loser.',
  huntMasteredTrapsDiffer: 'Next time, the traps will be different.',
  featherOneLookAtMine: 'Look at all my feathers. You got one left.',
  featherOnePlucked: 'You plucked yourself. I don’t even need to be here.',
  featherOneAroundHere: 'One left. Around here, you get plucked.',
  featherOneWait: 'That’s your last feather. I’ll wait.',
  featherOneCheck: 'That’s check.',
} as const;

export type PollyLineId = keyof typeof POLLY_LINES;

export type PollyMoment = {
  lineId: PollyLineId;
  line: string;
};

export function pollyMoment(lineId: PollyLineId): PollyMoment {
  return { lineId, line: POLLY_LINES[lineId] };
}
