export const POLLY_LINES = {
  homeBackAgain: 'Back again?',
  homeMissMe: 'Miss me?',
  homeMissingMeanings: 'Still missing a few meanings, aren’t you.',
  homeLoseFeathers: 'Come to lose some feathers?',
  homeWordsAsked: 'The words asked about you. I lied.',
  homeYourHighness: 'The name’s Polly. But you may call me Your Highness.',
  homeChamp: 'The champ is here. Me. I’m the champ.',
  homeCracker: 'And no, I don’t want a cracker.',
  homeGoAgain: 'Let’s go again.',
  homeReady: 'Are you ready? Because I’m ready.',
  homeDoubleOrNothing: 'Double or nothing.',
  homeCrown: 'I see you eyeing my crown.',
  homeFirstMeeting: 'Who are you? What do you want?',
  bossCage: 'I was still in the cage when I learned that one.',
  bossForYou: 'This one’s for you.',
  bossWroteMyself: 'I wrote this one myself.',
  bossWaiting: 'I’ve been waiting to use this.',
  bossFavorite: 'Here we go. My favorite.',
  bossPutWork: 'I put work into this one.',
  huntLaugh: 'BBBLAAAAHHAHAHA!',
  huntCleanSweep: "Bet you can't do that again.",
  huntThoughtSo: 'Thought so.',
  huntGotcha: 'Gotcha.',
  huntThereItIs: 'There it is.',
  huntEveryTime: 'Every time.',
  huntStillWorks: 'Still works.',
  huntPointToMe: 'Point to me.',
  huntAllMe: 'That’s all me.',
  huntGoodIsntIt: 'Good, isn’t it.',
  huntLoveThisGame: 'I love this game.',
  huntMyHouse: 'This is MY house.',
  huntWalkedRightIn: 'Walked right into that one.',
  huntGotMeCrowned: 'That one got me crowned.',
  huntZing: 'Zing!',
  huntStreakSoWhat: 'So what.',
  huntStreakEasy: 'Those were easy.',
  huntStreakWhosCounting: 'But who’s counting?',
  huntStreakLetYouHave: 'I let you have those.',
  huntStreakWarmUp: 'That was the warm-up.',
  huntStreakPacing: 'I’m pacing myself.',
  streakLucky: 'Lucky.',
  streakYikes: 'YIKES!',
  streakNotOver: 'The Hunt isn’t over yet.',
  streakStillGetYa: 'I’m still gonna get ya.',
  streakBirdBrain: 'Bird brain. Me, I mean.',
  streakRuffling: 'You’re ruffling my feathers.',
  huntHesitation: 'YES... NO... MAYBE SO...',
  huntAreYouSure: 'Are you sure?',
  huntRemember: 'Remember me.',
  resultsTrapsRemember: 'My traps remember you.',
  resultsMeaningsPast: 'Some meanings got past you.',
  resultsMeaningsHaunt: 'Some meanings still haunt you.',
  resultsNobodySaw: 'Nobody saw that.',
  resultsNeverHappened: 'That never happened.',
  resultsAMoment: 'I’d like a moment.',
  resultsRude: 'Well. That was rude.',
  resultsDareYou: 'Do that again. I dare you.',
  resultsThatWasGood: 'Fine. That one was good.',
  resultsReadEveryOne: 'Every trap. You read every one.',
  resultsNothingToSay: 'I have nothing to say to you.',
  resultsIWroteThose: 'I wrote all of those, you know.',
  resultsTakingNotes: 'Take the night. I’m taking notes.',
  resultsGettingOld: 'This is getting old.',
  resultsEnjoyIt: 'Enjoy it while it lasts.',
  resultsAdjustments: 'I’m making adjustments.',
  resultsDontGetComfortable: 'Don’t get comfortable.',
  resultsNewOnesTonight: 'I’m writing new ones tonight.',
  resultsLuckyLately: 'You’ve been lucky a lot lately.',
  resultsIveNoticed: 'I’ve noticed. Obviously I’ve noticed.',
  resultsManyMore: 'There’s many more to come.',
  resultsSecondBest: 'That was my second best.',
  resultsGotOne: 'One. You got one.',
  dailyButterKnife: 'Sharp as a butter knife.',
  dailyLossBat: 'CAN’T BEAT THAT WITH A BAT.',
  dailyWinTomorrow: 'WON’T HAPPEN TOMORROW.',
  dailyNotToday: 'NOT TODAY.',
  huntIntro: 'Enter the Hunt. We’ll see who hunts who.',
  huntHauntIntro: 'I hunt you. I haunt you.',
  huntAbandonTaunt: 'See you later, loser.',
  huntMasteredTrapsDiffer: 'Next time, the traps will be different.',
} as const;

export type PollyLineId = keyof typeof POLLY_LINES;

export type PollyMoment = {
  lineId: PollyLineId;
  line: string;
};

export function pollyMoment(lineId: PollyLineId): PollyMoment {
  return { lineId, line: POLLY_LINES[lineId] };
}
